/**
 * @file express.d.ts
 * @description Module augmentation for Express's Request and Response types.
 *
 * WHY THIS FILE EXISTS:
 * TypeScript's type system is "closed" — third-party libraries define the
 * types for their objects. When `pino-http` attaches `.log` to `req`, and
 * when we attach custom properties (like `req.user` in auth middleware later),
 * TypeScript doesn't know about them unless we declare them explicitly.
 *
 * Module augmentation ("declaration merging") lets us extend existing
 * type definitions without modifying the original library files.
 *
 * IMPORTANT: This file must be included in your tsconfig's `include` paths.
 * It is already covered by `src/**\/*` in our tsconfig.json.
 *
 * HOW IT WORKS:
 * TypeScript merges these declarations with Express's original types.
 * After this file, `req.log` will be recognized as a Pino Logger everywhere.
 */

import type { Logger } from 'pino';
import type { JwtPayload } from '../services/auth.service';

// Augment Express's core namespace
declare global {
  namespace Express {
    interface Request {
      /**
       * Pino logger instance bound to this specific HTTP request.
       * Injected by pino-http middleware.
       * Use this for request-scoped logging — every log line will
       * automatically include the request ID for end-to-end tracing.
       *
       * @example
       *   req.log.info({ userId }, 'User authenticated');
       *   // Logs: { reqId: "abc123", userId: "...", msg: "User authenticated" }
       */
      log: Logger;

      /**
       * The unique request ID generated by pino-http.
       * Echoed back to the client via the X-Request-Id response header.
       */
      id: string;

      /**
       * Authenticated user payload — populated by the auth middleware.
       * Only available on routes protected by `authenticate`.
       */
      user?: JwtPayload;
    }
  }
}

// This empty export makes TypeScript treat this as a module (not a script),
// which is required for global augmentation to work correctly.
export {};
